/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "var(--color-on-secondary-container)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "on-primary": "var(--color-on-primary)",
        "on-background": "var(--color-on-background)",
        "on-primary-fixed-variant": "var(--color-on-primary-container)",
        "surface-variant": "var(--color-surface-variant)",
        "primary-fixed-dim": "var(--color-primary)",
        "primary-container": "var(--color-primary-container)",
        "inverse-surface": "var(--color-inverse-surface)",
        background: "var(--color-background)",
        "on-primary-container": "var(--color-on-primary-container)",
        "surface-bright": "var(--color-surface)",
        "secondary-container": "var(--color-secondary-container)",
        "outline-variant": "var(--color-outline-variant)",
        "on-secondary": "var(--color-on-secondary)",
        error: "var(--color-error)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "tertiary-container": "var(--color-tertiary-container)",
        "primary-fixed": "var(--color-primary-container)",
        "on-surface": "var(--color-on-surface)",
        "on-error-container": "var(--color-on-error-container)",
        "tertiary-fixed": "var(--color-tertiary-container)",
        surface: "var(--color-surface)",
        "error-container": "var(--color-error-container)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "surface-container-low": "var(--color-surface-container-low)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-container)",
        "surface-dim": "var(--color-surface-variant)",
        "secondary-fixed-dim": "var(--color-secondary)",
        primary: "var(--color-primary)",
        "surface-container-high": "var(--color-surface-container-high)",
        "surface-tint": "var(--color-primary)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "on-primary-fixed": "var(--color-on-primary)",
        "tertiary-fixed-dim": "var(--color-tertiary)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "on-error": "var(--color-on-error)",
        tertiary: "var(--color-tertiary)",
        secondary: "var(--color-secondary)",
        "on-tertiary": "var(--color-on-tertiary)",
        "on-tertiary-fixed": "var(--color-on-tertiary)",
        "inverse-primary": "var(--color-inverse-primary)",
        outline: "var(--color-outline)",
        "on-secondary-fixed": "var(--color-on-secondary)",
        "surface-container": "var(--color-surface-container)",
        "secondary-fixed": "var(--color-secondary-container)"
      },
      fontFamily: {
        headline: ["Manrope"],
        body: ["Manrope"],
        label: ["Manrope"],
        display: "Manrope"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      }
    },
  },
  plugins: [],
}
